name: dart_calculadora
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  path: ^1.9.0
  math_expressions: ^2.5.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
